### ISSUE TITLE
Support for outputTemplate in Console sink

### ISSUE THREAD

**Issue by vasicvuk** [davisb10/serilogger#11]
It would be nice if we have a configurable outputTemplate in Console sink as .Net serilog does.

For example:
```
outputTemplate: "[{Timestamp:u} {Level:u3}] {Message:lj}{NewLine}{Exception}
```

**Comment by webJose** [comment]
Agreed!  Watching...

**Comment by webJose** [comment]
Any updates on this one?

**Comment by davisb10** [comment]
Feel free to open a pull request for this. I no longer have the free time to add new features to this project. However, I can quickly review and merge any pull requests as they are created.
