### ISSUE TITLE
ForContext

### ISSUE THREAD

**Issue by dportugal-spinitar** [davisb10/serilogger#22]
How do would you accomplish doing context? It's a type of enrichment.

componentA.log.verbose("button 3 was clicked");
console output: ComponentA "button 3 was clicked"

SubComponentofA.log.verbose("button 2 was clicked");
console output: ComponentA.SubComponentofA button 2 was clicked

**Comment by nblumhardt** [comment]
I think `createChild()` might be what you're looking for:

```js
componentA.log = logger.createChild({context: 'ComponentA'});
```

Getting the `context` property to the console, I'm not sure about - the `includeProperties` argument to the console sink might go some way towards this. HTH!
