### ISSUE TITLE
why continue to support the non-compact seq format?

### ISSUE THREAD

**Issue by SimonCropp** [davisb10/serilogger#3]
isnt it considered deprecated? cc @nblumhardt

https://github.com/davisb10/serilogger/blob/master/src/seqSink.ts#L14

**Comment by nblumhardt** [comment]
I guess this comes down to whether there's a need to support Seq 3.2 and earlier; these are pretty old (multiple years) but still in use in some places.

**Comment by davisb10** [comment]
I did question about having it in or not, but figured I might as well leave it as it does allow the backwards compatibility to the older versions. I may wind up deprecating it sometime in the future. I have not decided yet.
