### ISSUE TITLE
Broken version 0.4.2 on npmjs.com

### ISSUE THREAD

**Issue by felix-rc** [davisb10/serilogger#32]
Version 0.4.2 on npmjs.com appears to only contain 1 file: package.json

![FireShot Capture 4746 - serilogger - npm - www npmjs com](https://user-images.githubusercontent.com/123995854/215590041-6f9d8bb7-94ad-47f3-96c1-de6641cb128e.png)

**Comment by davisb10** [comment]
Fixed with latest push as version 0.4.3. 

0.4.2 was pushed incorrectly.
