### ISSUE TITLE
0.4.3 broken on npmjs

### ISSUE THREAD

**Issue by felix-rc** [davisb10/serilogger#33]
Files are present on npmjs, but not under the dist folder as described in package.json: `"main": "dist/serilogger.js",`

ref -- #32

**Comment by davisb10** [comment]
@felix-rc Good catch. I have pushed a new version of 0.4.4.

I apologize for the last versions being broken. I was trying to cleanup the build/publish scripts and they weren't doing what I was expecting. This version looks better in npm now.
