### ISSUE TITLE
Question: Reason behind the fork please?

### ISSUE THREAD

**Issue by jonyeezs** [davisb10/serilogger#9]
Hi, i'm currently using [structured-log](https://www.npmjs.com/package/structured-log) and I stumbled upon your fork.

I'm aware of structured-log inactiveness and wondering if i should move to a different variation.

If there are other reasons for publishing a variation of structured-log, could please share?

As well would you find this package production ready (security-wise etc).

This would help me (and perhaps others make decisions as I am). Thanks again!

**Comment by davisb10** [comment]
Hello @jonyeezs,

I found the original project as we currently use Serilog and SEQ for our logging needs for our back end applications at my work. We started writing front-end applications and wanted the same logging experience. structured-log had that feature but it was written in plain javascript without the Typescript typings that I wanted as all our applications were going to be done in Typescript.

So in seeing that structured-log had became stale, I decided to fork it, fix some of the open issues and then publish it myself.

**Comment by jonyeezs** [comment]
Thank you. Will be evaluating this. And having such a quick reply gives me bit more confidence in this library 😉
